// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhmrYB6NCcexXhmw5FW1xLrhfxtntku4s',
    appId: '1:1035741614587:web:f8ae050f915f90df1e3b5e',
    messagingSenderId: '1035741614587',
    projectId: 'foodguru-e77cd',
    authDomain: 'foodguru-e77cd.firebaseapp.com',
    storageBucket: 'foodguru-e77cd.firebasestorage.app',
    measurementId: 'G-3RWLXSR1GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGIMieM-5z_3MKFGxIrr5XFTsnzrhWoG0',
    appId: '1:1035741614587:android:91c5b43e5e96713f1e3b5e',
    messagingSenderId: '1035741614587',
    projectId: 'foodguru-e77cd',
    storageBucket: 'foodguru-e77cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuM8RHxx_EgWfd6GCbGyIh9ZPx9OxvytQ',
    appId: '1:1035741614587:ios:d5eeac8deccac0b21e3b5e',
    messagingSenderId: '1035741614587',
    projectId: 'foodguru-e77cd',
    storageBucket: 'foodguru-e77cd.firebasestorage.app',
    iosClientId: '1035741614587-c7eesqovi9hcuoui5bjleli72j77rv31.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdevproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuM8RHxx_EgWfd6GCbGyIh9ZPx9OxvytQ',
    appId: '1:1035741614587:ios:d5eeac8deccac0b21e3b5e',
    messagingSenderId: '1035741614587',
    projectId: 'foodguru-e77cd',
    storageBucket: 'foodguru-e77cd.firebasestorage.app',
    iosClientId: '1035741614587-c7eesqovi9hcuoui5bjleli72j77rv31.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdevproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhmrYB6NCcexXhmw5FW1xLrhfxtntku4s',
    appId: '1:1035741614587:web:fadafb463cbe40271e3b5e',
    messagingSenderId: '1035741614587',
    projectId: 'foodguru-e77cd',
    authDomain: 'foodguru-e77cd.firebaseapp.com',
    storageBucket: 'foodguru-e77cd.firebasestorage.app',
    measurementId: 'G-VXLM7S5HH4',
  );
}
